// src/pages/contact.tsx
import React from "react"
import { navigate } from "gatsby-link"
import Layout from "../components/layout"
import SEO from "../components/seo"
import './main.scss';

export default class Contact extends React.Component {
  constructor(props) {
    super(props)
    this.state = { isValidated: false }
  }

  handleChange = e => {
    this.setState({ [e.target.name]: e.target.value })
  }

  handleSubmit = e => {
    e.preventDefault()
    const form = e.target

    const data = new FormData(form)

    data.append('form-name', form.getAttribute('name'));

    console.log(data);

    fetch("/", {
      method: "POST",
      body: data
    })
      .then(() => navigate(form.getAttribute("action")))
      .catch(error => alert(error))
  }

  render() {
    return (
      <Layout>
        <SEO title="Contact" />
        <form
          name="contact"
          method="post"
          action="/thanks/"
          data-netlify="true"
          data-netlify-honeypot="bot-field"
          onSubmit={this.handleSubmit}
        >
          <input type="hidden" name="form-name" value="contact" />
          <div hidden>
            <label>
              Don’t fill this out:{" "}
              <input name="bot-field" onChange={this.handleChange} />
            </label>
          </div>
          <input
            aria-label="Input your name"
            className="input"
            type={"text"}
            name={"name"}
            onChange={this.handleChange}
            id={"name"}
            required={true}
            placeholder="Your Name"
          />
          <input
            aria-label="Input your email"
            className="input"
            type={"email"}
            name={"email"}
            onChange={this.handleChange}
            id={"email"}
            required={true}
            placeholder="Your email"
          />
          <textarea
            aria-label="Input your message"
            className="textarea"
            name={"message"}
            onChange={this.handleChange}
            id={"message"}
            required={false}
            placeholder="Your Message"
            rows={10}
          />

          <button aria-label="Submit form" type="submit">
            Send
          </button>
        </form>
      </Layout>
    )
  }
}

// src/app/contact/contact.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.scss'],
})
export class ContactComponent implements OnInit {
  contactForm: FormGroup;

  constructor(
    private fb: FormBuilder,
  ) {
  }

  ngOnInit(): void {

    this.contactForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      name: ['', [Validators.required]],
      msg: ['', [Validators.required]],
      bot: ['']
    });
  }

  onSubmit() {
    if (!this.contactForm.valid) {
      alert('form not valid');
    }

    alert('submit form');
  }

}

<form
  name="contact"
  method="post"
  action="/blog/"
  data-netlify="true"
  data-netlify-honeypot="bot-field"
  [formGroup]="contactForm"
>
  <input type="hidden" name="form-name" value="contact"/>
  <div hidden>
    <label>
      Don’t fill this out:
      <input name="bot-field" formControlName="bot"/>
    </label>
  </div>

  <label>

  <input
    aria-label="Input your name"
    Name="input"
    type="text"
    name="name"
    formControlName="name"
    id="name"
    placeholder="Your Name"
  />
  <ng-container *ngIf="contactForm.get('name').errors && contactForm.get('name').dirty">
    <small class="input-error" *ngIf="contactForm.get('name').hasError('required')">
      A name is required
    </small>
  </ng-container>
  </label>

  <label>

  <input
    aria-label="Input your email"
    class="input"
    type="email"
    name="email"
    formControlName="email"
    id="email"
    placeholder="Your Email"
  />

  <ng-container *ngIf="contactForm.get('email').errors && contactForm.get('email').dirty">
    <small class="input-error" *ngIf="contactForm.get('email').hasError('required')">
      An email is required
    </small>
    <small class="input-error" *ngIf="contactForm.get('email').hasError('email')">
      Invalid email
    </small>
  </ng-container>
  </label>

  <label>
  <textarea
    aria-label="Input your message"
    class="textarea"
    name="msg"
    formControlName="msg"
    id="message"
    placeholder="Your Message"
    rows=10></textarea>
    <ng-container *ngIf="contactForm.get('msg').errors && contactForm.get('msg').dirty">
      <small class="input-error" *ngIf="contactForm.get('msg').hasError('required')">
        A message is required
      </small>
    </ng-container>

  </label>
  <button tabindex="0" aria-label="Submit form" type="submit" [disabled]="!contactForm.valid">
    Send
  </button>
</form>
